ci(repo): improve release workflows [skip ci]

diff --git a/.github/workflows/maintenance-release.yml b/.github/workflows/maintenance-release.yml
--- a/.github/workflows/maintenance-release.yml
+++ b/.github/workflows/maintenance-release.yml
@@ -3,10 +3,14 @@ name: Release maintenance
 on:
   workflow_dispatch:
     inputs:
-      branch:
-        type: string
-        description: 'Maintenance branch to release from (e.g., package-name@1.x or package-name@1.0.x)'
-        required: true
+      skip-nx-cache:
+        type: boolean
+        description: 'Skip NX cache'
+        default: false
+      publish:
+        type: boolean
+        description: 'Publish to npm'
+        default: true
 
 env:
   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
@@ -15,6 +19,14 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate branch input
+        run: |
+          branch=${GITHUB_REF#refs/heads/}
+          if [[ ! "$branch" =~ ^[a-zA-Z0-9_-]+@[0-9]+\.([0-9]+|x)\.x$ ]]; then
+            echo "Error: Branch $branch is not a maintenance branch"
+            exit 1
+          fi
+
       - name: Check out Git repository
         uses: actions/checkout@v4
         with:
@@ -33,23 +45,25 @@ jobs:
       - name: Set up git bot user
         uses: snow-actions/git-config-user@v1.0.0
 
-      - name: Generate coverage badge
-        run: npx nx run-many -t coverage-badge
+      - name: Derive appropriate SHAs for base and head for `nx affected` commands
+        if: ${{ !env.ACT }}
+        uses: nrwl/nx-set-shas@v4
 
-      - name: Validate branch input
+      - name: Generate coverage badge
         run: |
-          branch=${{ github.event.inputs.branch }}
-          if [[ ! "$branch" =~ ^[a-zA-Z0-9-_]+@[0-9]+\.[0-9]*\.?x$ ]]; then
-            echo "Invalid branch format: $branch"
-            exit 1
-          fi
+          npx nx affected -t coverage-badge --skipNxCache=${{ inputs.skip-nx-cache }}
+          git add .
 
       - name: Create maintenance release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: npx nx release --skip-publish --dry-run=${{ !env.ACT }}
+        run: npx nx release --skip-publish --dry-run=${{ env.ACT || 'false'  }}
 
       - name: Publish
+        if: ${{ inputs.publish }}
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
-        run: npx nx release publish --tag ${{ github.event.inputs.branch }} --dry-run=${{ !env.ACT }}
+        run: npx nx release publish \
+          --tag ${{ github.event.inputs.branch }} \
+          --skipNxCache=${{ inputs.skip-nx-cache }} \
+          --dry-run=${{ env.ACT || 'false'  }}
diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -2,6 +2,15 @@ name: Release pre-release
 
 on:
   workflow_dispatch:
+    inputs:
+      skip-nx-cache:
+        type: boolean
+        description: 'Skip NX cache'
+        default: false
+      publish:
+        type: boolean
+        description: 'Publish to npm'
+        default: true
 
 env:
   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
@@ -11,6 +20,16 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Determine release channel
+        id: get-channel
+        run: |
+          branch=${GITHUB_REF#refs/heads/}
+          if [[ "$branch" != "alpha" && "$branch" != "beta" && "$branch" != "next" ]]; then
+            echo "Error: Branch '$branch' is not a valid pre-release branch. Valid options are: alpha, beta, or next."
+            exit 1
+          fi
+          echo "channel=$branch" >> $GITHUB_OUTPUT
+
       - name: Check out Git repository
         uses: actions/checkout@v4
         with:
@@ -29,18 +48,14 @@ jobs:
       - name: Set up git bot user
         uses: snow-actions/git-config-user@v1.0.0
 
-      - name: Generate coverage badge
-        run: npx nx run-many -t coverage-badge
+      - name: Derive appropriate SHAs for base and head for `nx affected` commands
+        if: ${{ !env.ACT }}
+        uses: nrwl/nx-set-shas@v4
 
-      - name: Determine release channel
-        id: get-channel
+      - name: Generate coverage badge
         run: |
-          branch=$(echo ${GITHUB_REF#refs/heads/})
-          if [[ "$branch" != "alpha" && "$branch" != "beta" && "$branch" != "next" ]]; then
-            echo "Error: Branch $branch is not a pre-release branch (alpha, beta, or next)."
-            exit 1
-          fi
-          echo "channel=$branch" >> $GITHUB_OUTPUT
+          npx nx affected -t coverage-badge --skipNxCache=${{ inputs.skip-nx-cache }}
+          git add .
 
       - name: Create version
         env:
@@ -70,13 +85,8 @@ jobs:
             --git-commit \
             --git-tag=false \
             --git-push \
-            --dry-run=${{ !env.ACT }}
+            --dry-run=${{ env.ACT || 'false'  }}
         #    --from=${{ steps.get-from-tag.outputs.tag }}
-
-      - name: Publish
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
-        run: npx nx release publish --tag ${{ steps.get-channel.outputs.channel }} --dry-run=${{ !env.ACT }}
 
       # - name: Tag last-prerelease
       #   shell: bash
@@ -90,3 +100,12 @@ jobs:
           branch: ${{ github.ref }}
           tags: true
           # force: true
+
+      - name: Publish
+        if: ${{ inputs.publish }}
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
+        run: npx nx release publish \
+          --tag ${{ steps.get-channel.outputs.channel }} \
+          --skipNxCache=${{ inputs.skip-nx-cache }} \
+          --dry-run=${{ env.ACT || 'false'  }}
