build(repo): fix pre-releases [skip ci]

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -2,18 +2,10 @@ name: Release pre-release
 
 on:
   workflow_dispatch:
-    inputs:
-      branch:
-        type: choice
-        description: 'Pre-release branch to release from'
-        required: true
-        options:
-          - alpha
-          - beta
-          - next
 
 env:
   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
+  HUSKY: 0
 
 jobs:
   release:
@@ -41,24 +33,56 @@ jobs:
         id: get-channel
         run: |
           branch=$(echo ${GITHUB_REF#refs/heads/})
+          if [[ "$branch" != "alpha" && "$branch" != "beta" && "$branch" != "next" ]]; then
+            echo "Error: Branch $branch is not a pre-release branch (alpha, beta, or next)."
+            exit 1
+          fi
           echo "channel=$branch" >> $GITHUB_OUTPUT
 
-      - name: Create pre-release
+      - name: Create version
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: npx nx release version prerelease --preid=${{ steps.get-channel.outputs.channel }} --git-tag
 
-      - name: Check if a new tag was created
-        id: check-tag
+      - name: Get the tag that was just created
+        id: get-latest-tag
         run: |
-          if git tag --points-at HEAD | grep -q .; then
-            echo "created=true" >> $GITHUB_OUTPUT
-          else
-            echo "created=false" >> $GITHUB_OUTPUT
-          fi
+          latest_tag=$(git describe --tags --abbrev=0)
+          semver=${latest_tag#*@}
+          echo "tag=$semver" >> $GITHUB_OUTPUT
+
+      # - name: Get the last pre-release tag
+      #   id: get-from-tag
+      #   run: |
+      #     if git rev-parse -q --verify "refs/tags/last-${{ steps.get-channel.outputs.channel }}" >/dev/null; then
+      #       echo "tag=last-${{ steps.get-channel.outputs.channel }}" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "tag=HEAD" >> $GITHUB_OUTPUT
+      #     fi
+      - name: Create changelog
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          npx nx release changelog ${{ steps.get-latest-tag.outputs.tag }} \
+            --git-commit \
+            --git-tag=false \
+            --git-push
+        #    --from=${{ steps.get-from-tag.outputs.tag }}
 
       - name: Publish
-        if: steps.check-tag.outputs.created == 'true'
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
         run: npx nx release publish --tag ${{ steps.get-channel.outputs.channel }}
+
+      # - name: Tag last-prerelease
+      #   shell: bash
+      #   run: git tag -f last-${{ steps.get-channel.outputs.channel }}
+
+      # TODO: https://github.com/nrwl/nx/issues/22073
+      - name: Push changes
+        uses: ad-m/github-push-action@v0.8.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
+          tags: true
+          # force: true
